version: '3.4'

services:
  envoy:
    image: envoy:latest
    container_name: envoy
    build:
      context: ./envoy
      dockerfile: Dockerfile
    depends_on:
      - greeterservice
    ports:
      - "8811:8811"
      - "8812:8812"
    network_mode: host

  #nginx:
  #  image: nginx:latest
  #  container_name: nginx
  #  restart: always
  #  depends_on:
  #    - greeterservice
  #  ports:
  #    - "50050:50050"
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./nginx/logs/:/var/log/nginx/

  greeterservice:
    image: ${DOCKER_REGISTRY-}greeterservice
    build:
      context: .
      dockerfile: GreeterService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5001:5001"