version: '3.4'

services:
  greeter-envoy:
    image: greeter-envoy:latest
    container_name: greeter-envoy
    build:
      context: ./envoy
      dockerfile: Dockerfile
    depends_on:
      - greeter-service
    ports:
      - "8080:8080"
      - "9902:9902"

  greeter-service:
    image: ${DOCKER_REGISTRY-}greeter-service
    build:
      context: .
      dockerfile: GreeterService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5001:5001"