version: '3.4'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - greeterservice
    ports:
      - "50050:50050"
      - "50051:50051"
      - "50052:50052"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/cert/server.crt:/etc/ssl/certs/server.crt:ro
      - ./nginx/cert/server.key:/etc/ssl/private/server.key:ro
      - ./nginx/logs/:/var/log/nginx/

  greeterservice:
    image: ${DOCKER_REGISTRY-}greeterservice
    build:
      context: .
      dockerfile: GreeterService/Dockerfile
    ports:
      - "5051:5051"
      - "5054:5054"
      - "5055:5055"